name: curentfitness2.com
favicon: null
layout_spectrum: 0.46019226708449423
typography_spectrum: 0.14717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9c9c7'
    - '#4b4c00'
    - '#6b7400'
    - '#232323'
    - '#00b3ba'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.04634304973296821
  rhythmicContrast: 0.786866215756163
purpose: []
